DROP DATABASE IF EXISTS EngineDB;
CREATE DATABASE EngineDB;
USE EngineDB;

DROP TABLE IF EXISTS document;
CREATE TABLE document(did INTEGER PRIMARY KEY, url VARCHAR(100) NOT NULL, title VARCHAR(100));

DROP TABLE IF EXISTS term;
CREATE TABLE term(tid INTEGER PRIMARY KEY, str VARCHAR(100) UNIQUE NOT NULL, idf INTEGER NOT NULL);

DROP TABLE IF EXISTS posting_list;
CREATE TABLE posting_list(tid INTEGER REFERENCES term(tid), did INTEGER REFERENCES document(did), tf INTEGER NOT NULL, PRIMARY KEY(tid, did));